// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZDxGw1F72pAk4Kv8Q2v5m-9ZuaQZ_i9k',
    appId: '1:408521327876:web:e24a9c13ef7429cad9bc51',
    messagingSenderId: '408521327876',
    projectId: 'farm-tech-1a96c',
    authDomain: 'farm-tech-1a96c.firebaseapp.com',
    storageBucket: 'farm-tech-1a96c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJYXc_E58NvFosRSAUeJOpdB47ATRFGBs',
    appId: '1:408521327876:android:d666da1f880c647cd9bc51',
    messagingSenderId: '408521327876',
    projectId: 'farm-tech-1a96c',
    storageBucket: 'farm-tech-1a96c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Sc6UIMGcw_YIPdU51iMLsMv-U3vSHcw',
    appId: '1:408521327876:ios:18b66037476dc2c4d9bc51',
    messagingSenderId: '408521327876',
    projectId: 'farm-tech-1a96c',
    storageBucket: 'farm-tech-1a96c.appspot.com',
    iosBundleId: 'com.example.farmTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Sc6UIMGcw_YIPdU51iMLsMv-U3vSHcw',
    appId: '1:408521327876:ios:18b66037476dc2c4d9bc51',
    messagingSenderId: '408521327876',
    projectId: 'farm-tech-1a96c',
    storageBucket: 'farm-tech-1a96c.appspot.com',
    iosBundleId: 'com.example.farmTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZDxGw1F72pAk4Kv8Q2v5m-9ZuaQZ_i9k',
    appId: '1:408521327876:web:689702b40d6235f8d9bc51',
    messagingSenderId: '408521327876',
    projectId: 'farm-tech-1a96c',
    authDomain: 'farm-tech-1a96c.firebaseapp.com',
    storageBucket: 'farm-tech-1a96c.appspot.com',
  );
}
